# Generated by Django 5.1.3 on 2024-11-13 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_note_options'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shared',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes', to='note.note'),
        ),
        migrations.AlterField(
            model_name='shared',
            name='shared',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='shared',
            unique_together={('note', 'shared')},
        ),
    ]
