# Generated by Django 5.1.3 on 2024-11-15 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_shared_can_view_alter_shared_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='shared',
            old_name='shared',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='shared',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shared',
            name='permission',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shared',
            name='shared_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shared',
            name='shared_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shared_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='shared',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='shared',
            name='can_view',
        ),
    ]
