# Generated by Django 5.1.3 on 2024-11-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shared_note',
                'managed': False,
            },
        ),
    ]
