# Generated by Django 5.1.3 on 2024-11-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'managed': False},
        ),
    ]
