# Generated by Django 5.1.3 on 2024-11-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('type', models.IntegerField()),
                ('create_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'note',
                'managed': False,
            },
        ),
    ]
