# Generated by Django 5.1.3 on 2024-11-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
    ]
