# Generated by Django 5.1.3 on 2024-11-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_note_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
