# Generated by Django 5.1.3 on 2024-11-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_note_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
