# Generated by Django 5.1.3 on 2024-11-17 10:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_note_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shared_with',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
