# Generated by Django 5.1.3 on 2024-11-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_note_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='shared_with',
        ),
    ]
