# Generated by Django 5.1.3 on 2024-11-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
    ]
